apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: ai-interview-platform
data:
  PORT: "8000"
  MONGO_DB: "ai_interview_platform"
  # Other non-sensitive config variables go here
